context:
  version: "0.19.0"
  mojo_version: "=0.25.7"

package:
  name: "extramojo"
  version: ${{ version }}

source:
  - git: https://github.com/ExtraMojo/ExtraMojo.git
    rev: 6afbfc66b7d9840c82a20ea1090443934e31b673
  # path: .
  # use_gitignore: true

build:
  number: 0
  script:
    - mojo package extramojo -o ${{ PREFIX }}/lib/mojo/extramojo.mojopkg
requirements:
  build:
    - mojo-compiler ${{ mojo_version }}
  host:
    - mojo-compiler ${{ mojo_version }}
  run:
    - mojo-compiler ${{ mojo_version }}

tests:
  - script:
      - if: unix
        then:
          - sh -c 'find ./tests -name test_*.mojo | xargs -I % pixi run mojo run -I . -D ASSERT=all %'
    requirements:
      build:
        - mojo ${{ mojo_version }}
      run:
        - mojo ${{ mojo_version }}
    files:
      source:
        - extramojo/
        - tests/

about:
  homepage: https://github.com/ExtraMojo/ExtraMojo
  license: "Unlicense OR MIT"
  license_file:
    - LICENSE-MIT
    - UNLICENSE
  summary: Extra functionality not yet in the standard library, mostly focused on strings and file IO.
  repository: https://github.com/ExtraMojo/ExtraMojo

extra:
  maintainers:
    - sstadick
  project_name: extramojo
