context:
  version: "0.4.0"
  mojo_version: "=0.26.2"

package:
  name: "argmojo"
  version: ${{ version }}

source:
  - git: https://github.com/forfudan/argmojo.git
    rev: 2dbb8977ce02bc5b02f4e302839dcbb94c73e586

build:
  number: 0
  script:
    - mkdir -p ${PREFIX}/lib/mojo
    - mojo package src/argmojo -o ${{ PREFIX }}/lib/mojo/argmojo.mojopkg

requirements:
  host:
    - mojo-compiler ${{ mojo_version }}
  build:
    - mojo-compiler ${{ mojo_version }}
  run:
    - mojo-compiler ${{ mojo_version }}

about:
  homepage: https://github.com/forfudan/argmojo
  license: Apache-2.0
  license_file: LICENSE
  summary: A command-line argument parser library for Mojo.
  repository: https://github.com/forfudan/argmojo.git

extra:
  project_name: argmojo
  maintainers:
    - forfudan
