context:
  version: "0.6.0"
  mojo_version: "=0.25.7"

package:
  name: "decimojo"
  version: ${{ version }}

source:
  - git: https://github.com/forFudan/decimojo.git
    rev: 0fab1a2349cf05b854c4c204ec2121f634396809

build:
  number: 0
  script:
    - mkdir -p ${PREFIX}/lib/mojo
    - mojo package src/decimojo -o ${{ PREFIX }}/lib/mojo/decimojo.mojopkg

requirements:
  host:
    - mojo-compiler ${{ mojo_version }}
  build:
    - mojo-compiler ${{ mojo_version }}
  run:
    - mojo-compiler ${{ mojo_version }}

about:
  homepage: https://github.com/forFudan/decimojo.git
  license: Apache-2.0
  license_file: LICENSE
  summary: An arbitrary-precision decimal and integer mathematics library for Mojo
  repository: https://github.com/forFudan/decimojo.git

extra:
  project_name: decimojo
  maintainers:
    - forfudan
