[project]
name = "modular-community"
channels = ["conda-forge"]
platforms = ["linux-64", "linux-aarch64", "osx-arm64"]

[feature.build.tasks]
build-all = "python -m scripts.build-all"
upload = "python -m scripts.upload"
commit-changes = "python -m scripts.commit-changes"
remove-incompatible-packages = "python -m scripts.remove-incompatible-packages"
configure-git = "python -m scripts.configure-git"

[feature.build.dependencies]
rattler-build = ">=0.30.0,<0.31"
python = ">=3.13.0,<3.14"
pygithub = ">=2.5.0,<3"
pyyaml = ">=6.0.2,<7"
types-pyyaml = ">=6.0.12.20240917,<7"
conda = ">=25.5.1,<26"

[feature.lint.dependencies]
actionlint = ">=1.7.4,<2"
ruff = ">=0.7.3,<0.8"
check-jsonschema = ">=0.29.4,<0.30"
shellcheck = ">=0.10.0,<0.11"
mypy = ">=1.13.0,<2"

[feature.pre-commit.dependencies]
pre-commit = ">=4.0.1,<5"

[feature.pre-commit.tasks]
pre-commit-install = "pre-commit install"
lint = "pre-commit run -a"

[feature.docs.dependencies]
mkdocs = ">=1.6.1,<2"
mkdocs-material = ">=9.5.20,<10"

[feature.docs.tasks]
deploy-docs = "mkdocs gh-deploy --force"
docs = "mkdocs serve"

[environments]
default = ["build", "lint", "pre-commit"]
docs = ["docs"]
