context:
  version: "0.0.1"

package:
  name: "mist"
  version: ${{ version }}

source:
  - git: https://github.com/thatstoasty/small-time.git
    rev: 67fae584d1d4742a9421575c8a59d34cb84c14a3

build:
  number: 0
  script:
    - mojo package src/small-time -o ${{ PREFIX }}/lib/mojo/small-time.mojopkg
requirements:
  host:
    - max =24.6
  run:
    - ${{ pin_compatible('max') }}

tests:
  - script:
      - if: unix
        then:
          - mojo test test/test_small_time.mojo
    files:
      recipe:
        - test_small_time.mojo
        - test_time_delta.mojo
        - test_time_zone.mojo

about:
  homepage: https://github.com/thatstoasty/small-time
  # Remember to specify the license variants for BSD, Apache, GPL, and LGPL.
  # Use the SPDX identifier, e.g: GPL-2.0-only instead of GNU General Public License version 2.0
  # See https://spdx.org/licenses/
  license: Apache-2.0
  # It is strongly encouraged to include a license file in the package,
  # (even if the license doesn't require it) using the license_file entry.
  # See https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#license-file
  license_file: LICENSE
  summary: Datetime library forked from morrow.mojo
  repository: https://github.com/thatstoasty/small-time

extra:
  maintainers:
    - thatstoasty
