context:
  version: 0.1.4

package:
  name: "kelvin"
  version: ${{ version }}

source:
 - git: https://github.com/bgreni/Kelvin.git
   rev: 3018ba56fa762a3090bbf4ca26438b6c506278ea

build:
  number: 0
  script:
    - mojo package kelvin -o ${{ PREFIX }}/lib/mojo/kelvin.mojopkg

requirements:
  host:
    - mojo-compiler =0.25.7
  build:
    - mojo-compiler =0.25.7
  run:
    - ${{ pin_compatible('mojo-compiler') }}

tests:
  - script:
    - if: unix
      then:
        - python run_test.py
        - python scripts/generate_tests.py && python scripts/run_reject_tests.py

    files:
      source:
        - kelvin/
        - test/
        - run_test.py
        - scripts/run_reject_tests.py
        - scripts/generate_tests.py
    requirements:
      build:
        - mojo =0.25.7
      run:
        - mojo =0.25.7

about:
  homepage: https://github.com/bgreni/Kelvin
  license: Apache-2.0
  license_file: LICENSE
  summary: A powerful dimensional analysis library written in Mojo
  repository: https://github.com/bgreni/Kelvin

extra:
  maintainers:
    - bgreni
  project_name:
    - Kelvin