context:
  version: 0.3.0

package:
  name: "kelvin"
  version: ${{ version }}

source:
 - git: https://github.com/bgreni/Kelvin.git
   rev: 471409b4f1ac980be4beb5ba7de9a152d2e3f702

build:
  number: 0
  script:
    - mojo package kelvin -o ${{ PREFIX }}/lib/mojo/kelvin.mojopkg

requirements:
  host:
    - mojo-compiler =1.0.0
  build:
    - mojo-compiler =1.0.0
  run:
    - ${{ pin_compatible('mojo-compiler') }}

tests:
  - script:
    - if: unix
      then:
        - python run_test.py
        - python scripts/generate_tests.py && python scripts/run_reject_tests.py

    files:
      source:
        - kelvin/
        - test/
        - run_test.py
        - scripts/run_reject_tests.py
        - scripts/generate_tests.py
    requirements:
      build:
        - mojo =1.0.0
      run:
        - mojo =1.0.0

about:
  homepage: https://github.com/bgreni/Kelvin
  license: Apache-2.0
  license_file: LICENSE
  summary: A powerful dimensional analysis library written in Mojo
  repository: https://github.com/bgreni/Kelvin

extra:
  maintainers:
    - bgreni
  project_name:
    - Kelvin