context:
  version: "0.1.9"

package:
  name: "libc"
  version: ${{ version }}

source:
  - git: https://github.com/msaelices/mojo-libc.git
    rev: 674d0fd35af4e716eb30df18cb1fe25cdddb08cf

build:
  number: 0
  script:
    - mojo package src/libc -o ${PREFIX}/lib/mojo/libc.mojopkg

requirements:
  host:
    - max >= 25.2
  run:
    - ${{ pin_compatible('max') }}

about:
  homepage: https://github.com/msaelices/mojo-libc
  license: MIT
  license_file: LICENSE
  summary: Mojo's libc support
  repository: https://github.com/msaelices/mojo-libc

extra:
  maintainers:
    - msaelices
    - crisadamo
  project_name: mojo-libc
