context:
  version: 0.2.1

package:
  name: "emberjson"
  version: ${{ version }}

source:
 - git: https://github.com/bgreni/EmberJson.git
   rev: 6c6ed09fba6c426546e099af886deb53824bb4ba

build:
  number: 0
  script:
    - mojo package emberjson -o ${{ PREFIX }}/lib/mojo/emberjson.mojopkg

requirements:
  host:
    - mojo-compiler =0.25.7
  build:
    - mojo-compiler =0.25.7
  run:
    - ${{ pin_compatible('mojo-compiler') }}

tests:
  - script:
    - if: unix
      then:
        - python run_tests.py
    files:
      source:
        - run_tests.py
        - test/
        - emberjson/
        - bench_data/
    requirements:
      build:
        - mojo =0.25.7
      run:
        - mojo =0.25.7

about:
  homepage: https://github.com/bgreni/EmberJson
  license: Apache-2.0
  license_file: LICENSE
  summary: A lightweight JSON parsing library written in pure Mojo
  repository: https://github.com/bgreni/EmberJson

extra:
  maintainers:
    - bgreni
  project_name:
    - EmberJson