context:
  version: 0.3.0

package:
  name: "emberjson"
  version: ${{ version }}

source:
 - git: https://github.com/bgreni/EmberJson.git
   rev: 8ad6a4cd82853ecdad94f4dc3249c599694e251f

build:
  number: 0
  script:
    - mojo package emberjson -o ${{ PREFIX }}/lib/mojo/emberjson.mojopkg

requirements:
  host:
    - mojo-compiler =0.26.1
  build:
    - mojo-compiler =0.26.1
  run:
    - ${{ pin_compatible('mojo-compiler') }}

tests:
  - script:
    - if: unix
      then:
        - python run_tests.py
    files:
      source:
        - run_tests.py
        - test/
        - emberjson/
        - bench_data/
    requirements:
      build:
        - mojo =0.26.1
      run:
        - mojo =0.26.1

about:
  homepage: https://github.com/bgreni/EmberJson
  license: Apache-2.0
  license_file: LICENSE
  summary: A lightweight JSON parsing library written in pure Mojo
  repository: https://github.com/bgreni/EmberJson

extra:
  maintainers:
    - bgreni
  project_name:
    - EmberJson