# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
context:
  version: "0.25.6"
  mojo_version: "=0.25.6"
package:
  name: "lightbug_http"
  version: ${{ version }}
source:
  - git: https://github.com/saviorand/lightbug_http.git
    rev: b7b81a8332259fa14e1057dc86a8249c2e6df927
build:
  number: 0
  script:
    - mkdir -p ${PREFIX}/lib/mojo
    - mojo package lightbug_http -o ${{ PREFIX }}/lib/mojo/lightbug_http.mojopkg
requirements:
  build:
    - mojo-compiler ${{ mojo_version }}
  host:
    - mojo-compiler ${{ mojo_version }}
  run:
    - mojo-compiler ${{ mojo_version }}
tests:
  - script:
      - if: unix
        then:
          - mojo test
    requirements:
      build:
        - mojo ${{ mojo_version }}
      run:
        - mojo ${{ mojo_version }}
    files:
      recipe:
        - tests/lightbug_http/io/test_bytes.mojo
        - tests/lightbug_http/test_client.mojo
        - tests/lightbug_http/test_cookie.mojo
        - tests/lightbug_http/test_header.mojo
        - tests/lightbug_http/test_http.mojo
        - tests/lightbug_http/test_net.mojo
        - tests/lightbug_http/test_uri.mojo
about:
  homepage: https://lightbug.site
  license: MIT
  license_file: LICENSE
  summary: Lightbug is a simple and sweet HTTP framework for Mojo
  repository: https://github.com/saviorand/lightbug_http
extra:
  maintainers:
    - saviorand
    - bgreni
    - thatstoasty
  project_name: lightbug_http
