context:
  version: "0.1.0"

package:
  name: "mojmelo"
  version: ${{ version }}

source:
  - git: https://github.com/yetalit/mojmelo.git
    rev: 01692d2078e55f4dbeac981240edc620d0dc96af

build:
  number: 0
  script:
    - mojo package pixi/mojmelo/utils/mojmelo_matmul -o ${{ PREFIX }}/lib/mojo/mojmelo_matmul.mojopkg
    - mojo package pixi/mojmelo -o ${{ PREFIX }}/lib/mojo/mojmelo.mojopkg
requirements:
  host:
    - mojo-compiler =0.25.7
  run:
    - ${{ pin_compatible('mojo-compiler') }}

tests:
  - script:
      - if: unix
        then:
          - mojo tests/setup.mojo
    requirements:
      run:
        - mojo-compiler =0.25.7
    files:
      recipe:
        - tests/setup.mojo
        - tests/setup.sh
        - tests/mojmelo/__init__.mojo
        - tests/mojmelo/utils/*.mojo
        - tests/mojmelo/utils/mojmelo_matmul/*.mojo

about:
  homepage: https://github.com/yetalit/Mojmelo
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Machine Learning algorithms in pure Mojo.
  repository: https://github.com/yetalit/Mojmelo

extra:
  project_name: Mojmelo
  maintainers:
    - yetalit
