context:
  version: "0.1.5"

package:
  name: "mojmelo"
  version: ${{ version }}

source:
  - git: https://github.com/yetalit/mojmelo.git
    rev: 3ea2468262f11ae918f69e6337174a078fa9d3a4

build:
  number: 1
  script:
    - mojo precompile pixi/mojmelo/utils/mojmelo_matmul -o ${{ PREFIX }}/lib/mojo/mojmelo_matmul.mojoc
    - mojo precompile pixi/mojmelo -o ${{ PREFIX }}/lib/mojo/mojmelo.mojoc
requirements:
  host:
    - mojo-compiler >=1.0.0,<2
  run:
    - ${{ pin_compatible('mojo-compiler') }}

tests:
  - script:
      - if: unix
        then:
          - mojo tests/setup.mojo
    requirements:
      run:
        - mojo-compiler >=1.0.0,<2
    files:
      recipe:
        - tests/setup.mojo
        - tests/setup.sh
        - tests/mojmelo_tmp/__init__.mojo
        - tests/mojmelo_tmp/utils/*.mojo
        - tests/mojmelo_tmp/utils/mojmelo_matmul/*.mojo

about:
  homepage: https://github.com/yetalit/Mojmelo
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Machine Learning algorithms in pure Mojo.
  repository: https://github.com/yetalit/Mojmelo

extra:
  project_name: Mojmelo
  maintainers:
    - yetalit
